### ISSUE TITLE
Build skeleton of vignette

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/distcrete#4]
I'll write a few paragraphs with empty code chunks for you to fill. Should be a fun (ish) way to see how well the use-case has been laid out :) 

Note: if you'd rather, can be done in the README.Rmd

**Comment by richfitz** [comment]
So, I have this done on my laptop but found a critical off-by-one issue that means everything is a bit stuffed

**Comment by richfitz** [comment]
My preference is always for a small README, most of the stuff in the vignette

**Comment by thibautjombart** [comment]
Vignette then ;) 
I had written 'your package, your rules', but I know I would regret this statement eventually :p
